src/Entity/MateriauxNecessaires.php
<?php

namespace App\Entity;

use App\Repository\MateriauxNecessairesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MateriauxNecessairesRepository::class)
 */
class MateriauxNecessaires
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $quantite_prevue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $quantite_utilisee;

    /**
     * @ORM\ManyToOne(targetEntity=Materiaux::class, inversedBy="materiauxNecessaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $materiaux;

    /**
     * @ORM\ManyToOne(targetEntity=Tache::class, inversedBy="materiauxNecessaires",  cascade={ "remove"})
     */
    private $tache;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantitePrevue(): ?float
    {
        return $this->quantite_prevue;
    }

    public function setQuantitePrevue(float $quantite_prevue): self
    {
        $this->quantite_prevue = $quantite_prevue;

        return $this;
    }

    public function getQuantiteUtilisee(): ?string
    {
        return $this->quantite_utilisee;
    }

    public function setQuantiteUtilisee(string $quantite_utilisee): self
    {
        $this->quantite_utilisee = $quantite_utilisee;

        return $this;
    }

    public function getMateriaux(): ?Materiaux
    {
        return $this->materiaux;
    }

    public function setMateriaux(?Materiaux $materiaux): self
    {
        $this->materiaux = $materiaux;

        return $this;
    }

    public function getTache(): ?Tache
    {
        return $this->tache;
    }

    public function setTache(?Tache $tache): self
    {
        $this->tache = $tache;

        return $this;
    }

    /**
     * The __toString method allows a class to decide how it will react when it is converted to a string.
     *
     * @return string
     * @link https://php.net/manual/en/language.oop5.magic.php#language.oop5.magic.tostring
     */
    public function __toString()
    {
       return $this->getMateriaux()." pour ".$this->getTache();
    }

}

src/Form/MateriauxNecessairesType.php
<?php

namespace App\Form;

use App\Entity\MateriauxNecessaires;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MateriauxNecessairesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantite_prevue')
            ->add('quantite_utilisee')
            ->add('materiaux')
            ->add('tache')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MateriauxNecessaires::class,
        ]);
    }
}

src/Controller/MateriauxNecessairesController.php
<?php

namespace App\Controller;

use App\Entity\MateriauxNecessaires;
use App\Form\MateriauxNecessairesType;
use App\Repository\MateriauxNecessairesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/conduc/necessaire/materiaux')]
class MateriauxNecessairesController extends AbstractController
{
    #[Route('', name: 'materiaux_necessaires_index', methods: ['GET'])]
    #ParamConverter("id", class="MateriauxNecessaires", options={"id": "id"})
    public function index(MateriauxNecessairesRepository $materiauxNecessairesRepository): Response
    {
        return $this->render('materiaux_necessaires/index.html.twig', [
            'materiaux_necessaires' => $materiauxNecessairesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'materiaux_necessaires_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $materiauxNecessaire = new MateriauxNecessaires();
        $form = $this->createForm(MateriauxNecessairesType::class, $materiauxNecessaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($materiauxNecessaire);
            $entityManager->flush();
            $route = $request->headers->get('referer');

            return $this->redirect($route);
            //return $this->redirectToRoute('materiaux_necessaires_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materiaux_necessaires/new.html.twig', [
            'materiaux_necessaire' => $materiauxNecessaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'materiaux_necessaires_show', methods: ['GET'])]
    public function show(MateriauxNecessaires $materiauxNecessaire): Response
    {
        return $this->render('materiaux_necessaires/show.html.twig', [
            'materiaux_necessaire' => $materiauxNecessaire,
        ]);
    }

    #[Route('/{id}/edit', name: 'materiaux_necessaires_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, MateriauxNecessaires $materiauxNecessaire, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MateriauxNecessairesType::class, $materiauxNecessaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $route = $request->headers->get('referer');

            return $this->redirect($route);
            //return $this->redirectToRoute('materiaux_necessaires_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materiaux_necessaires/edit.html.twig', [
            'materiaux_necessaire' => $materiauxNecessaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'materiaux_necessaires_delete', methods: ['POST'])]
    public function delete(Request $request, MateriauxNecessaires $materiauxNecessaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$materiauxNecessaire->getId(), $request->request->get('_token'))) {
            $entityManager->remove($materiauxNecessaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('materiaux_necessaires_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/materiaux_necessaires/_delete_form.html.twig
<form method="post" action="{{ path('materiaux_necessaires_delete', {'id': materiaux_necessaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ materiaux_necessaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/materiaux_necessaires/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/materiaux_necessaires/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MateriauxNecessaires{% endblock %}

{% block body %}
    <h1>Edit MateriauxNecessaires</h1>

    {{ include('materiaux_necessaires/_form.html.twig', {'button_label': 'Update'}) }}

    <button class="btn btn-primary" onclick="goBack()">Retour</button>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>

    {{ include('materiaux_necessaires/_delete_form.html.twig') }}
{% endblock %}

templates/materiaux_necessaires/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MateriauxNecessaires index{% endblock %}

{% block body %}
    <h1>MateriauxNecessaires index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantite_prevue</th>
                <th>Quantite_utilisee</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for materiaux_necessaire in materiaux_necessaires %}
            <tr>
                <td>{{ materiaux_necessaire.id }}</td>
                <td>{{ materiaux_necessaire.quantitePrevue }}</td>
                <td>{{ materiaux_necessaire.quantiteUtilisee }}</td>
                <td>
                    <a href="{{ path('materiaux_necessaires_show', {'id': materiaux_necessaire.id}) }}">show</a>
                    <a href="{{ path('materiaux_necessaires_edit', {'id': materiaux_necessaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('materiaux_necessaires_new') }}">Create new</a>
{% endblock %}

templates/materiaux_necessaires/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New MateriauxNecessaires{% endblock %}

{% block body %}
    <h1>Create new MateriauxNecessaires</h1>

    {{ include('materiaux_necessaires/_form.html.twig') }}

    <button class="btn btn-primary" onclick="goBack()">Retour</button>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

templates/materiaux_necessaires/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MateriauxNecessaires{% endblock %}

{% block body %}
    <h1>MateriauxNecessaires</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ materiaux_necessaire.id }}</td>
            </tr>
            <tr>
                <th>Quantite_prevue</th>
                <td>{{ materiaux_necessaire.quantitePrevue }}</td>
            </tr>
            <tr>
                <th>Quantite_utilisee</th>
                <td>{{ materiaux_necessaire.quantiteUtilisee }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('materiaux_necessaires_index') }}">back to list</a>

    <a href="{{ path('materiaux_necessaires_edit', {'id': materiaux_necessaire.id}) }}">edit</a>

    {{ include('materiaux_necessaires/_delete_form.html.twig') }}
{% endblock %}