src/Entity/Metier.php
<?php

namespace App\Entity;

use App\Repository\MetierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;

/**
 * @ORM\Entity(repositoryClass=MetierRepository::class)
 */
class Metier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $corps_metier;

    /**
     * @ORM\ManyToMany(targetEntity=Prestataire::class, inversedBy="metiers")
     */
    private $prestataires;

    /**
     * @ORM\OneToMany(targetEntity=Tache::class, mappedBy="metier")
     */
    private $taches;

    public function __construct()
    {
        $this->prestataires = new ArrayCollection();
        $this->taches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCorpsMetier(): ?string
    {
        return $this->corps_metier;
    }

    public function setCorpsMetier(string $corps_metier): self
    {
        $this->corps_metier = $corps_metier;

        return $this;
    }

    /**
     * @return Collection|Prestataire[]
     */
    public function getPrestataires(): Collection
    {
        return $this->prestataires;
    }

    public function addPrestataire(Prestataire $prestataire): self
    {
        if (!$this->prestataires->contains($prestataire)) {
            $this->prestataires[] = $prestataire;
        }

        return $this;
    }

    public function removePrestataire(Prestataire $prestataire): self
    {
        $this->prestataires->removeElement($prestataire);

        return $this;
    }

    public function __toString()
    {
        return $this->corps_metier;

    }

    /**
     * @return Collection|Tache[]
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): self
    {
        if (!$this->taches->contains($tach)) {
            $this->taches[] = $tach;
            $tach->setMetier($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): self
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getMetier() === $this) {
                $tach->setMetier(null);
            }
        }

        return $this;
    }


}

src/Form/MetierType.php
<?php

namespace App\Form;

use App\Entity\Metier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MetierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('corps_metier')
            ->add('prestataires')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Metier::class,
        ]);
    }
}

src/Controller/MetierController.php
<?php

namespace App\Controller;

use App\Entity\Metier;
use App\Form\MetierType;
use App\Repository\MetierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/conduc/metier')]
class MetierController extends AbstractController
{
    #[Route('/', name: 'metier_index', methods: ['GET'])]
    public function index(MetierRepository $metierRepository): Response
    {
        return $this->render('metier/index.html.twig', [
            'metiers' => $metierRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'metier_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $metier = new Metier();
        $form = $this->createForm(MetierType::class, $metier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($metier);
            $entityManager->flush();

            return $this->redirectToRoute('metier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('metier/new.html.twig', [
            'metier' => $metier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'metier_show', methods: ['GET'])]
    public function show(Metier $metier): Response
    {
        
        return $this->render('metier/show.html.twig', [
            'metier' => $metier,
        ]);
    }

    #[Route('/{id}/edit', name: 'metier_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Metier $metier): Response
    {
        $form = $this->createForm(MetierType::class, $metier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('metier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('metier/edit.html.twig', [
            'metier' => $metier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'metier_delete', methods: ['POST'])]
    public function delete(Request $request, Metier $metier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$metier->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($metier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('metier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/metier/_delete_form.html.twig
<form method="post" action="{{ path('metier_delete', {'id': metier.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ metier.id) }}">
    <button class="btn btn-outline-danger mx-auto">Supprimer</button>
</form>

templates/metier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Metier{% endblock %}

{% block body %}
    <h1>Edit Metier</h1>

    {{ include('metier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('metier_index') }}">back to list</a>

    {{ include('metier/_delete_form.html.twig') }}
{% endblock %}

templates/metier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Metier index{% endblock %}

{% block body %}
    <h1>Metier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Corps_metier</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for metier in metiers %}
            <tr>
                <td>{{ metier.id }}</td>
                <td>{{ metier.corpsMetier }}</td>
                <td>
                    <a href="{{ path('metier_show', {'id': metier.id}) }}">show</a>
                    <a href="{{ path('metier_edit', {'id': metier.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('metier_new') }}">Create new</a>
{% endblock %}

templates/metier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Metier{% endblock %}

{% block body %}
    <h1>Create new Metier</h1>

    {{ include('metier/_form.html.twig') }}

    <a href="{{ path('metier_index') }}">back to list</a>
{% endblock %}

templates/metier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Metier{% endblock %}

{% block body %}
    <h1>Metier</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ metier.id }}</td>
            </tr>
            <tr>
                <th>Corps_metier</th>
                <td>{{ metier.corpsMetier }}</td>
            </tr>
            <tr>
                <th>Prestaires</th>
                <td>
                    {% for p in metier.prestataires %}
                        <li>{{ p }}</li>
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('metier_index') }}">back to list</a>

    <a href="{{ path('metier_edit', {'id': metier.id}) }}">edit</a>

    {{ include('metier/_delete_form.html.twig') }}
{% endblock %}