src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TacheRepository::class)
 */
class Tache
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_tache;

    /**
     * @ORM\Column(type="float")
     */
    private $tarif_prestation;

    /**
     * @ORM\OneToMany(targetEntity=MateriauxNecessaires::class, mappedBy="tache", cascade={ "remove"})
     */
    private $materiauxNecessaires;

    /**
     * @ORM\ManyToOne(targetEntity=Prestataire::class, inversedBy="taches")
     */
    private $prestataire;

    /**
     * @ORM\ManyToOne(targetEntity=Metier::class, inversedBy="taches")
     */
    private $metier;

    /**
     * @ORM\OneToMany(targetEntity=StockTacheUtilise::class, mappedBy="tache")
     */
    private $stockTacheUtilises;

    /**
     * @ORM\ManyToMany(targetEntity=Phase::class, inversedBy="taches")
     */
    private $phase;

    /**
     * @ORM\ManyToOne(targetEntity=Statut::class, inversedBy="taches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $statut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateDebut;



    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateFin;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $duree;

    /**
     * @ORM\ManyToOne(targetEntity=Tache::class, inversedBy="taches")
     */
    private $tache_dependante;

    /**
     * @ORM\OneToMany(targetEntity=Tache::class, mappedBy="tache_dependante")
     */
    private $taches;



    public function __construct()
    {
        $this->taches = new ArrayCollection();
        $this->materiauxNecessaires = new ArrayCollection();
        $this->stockTacheUtilises = new ArrayCollection();
        $this->phase = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomTache(): ?string
    {
        return $this->nom_tache;
    }

    public function setNomTache(string $nom_tache): self
    {
        $this->nom_tache = $nom_tache;

        return $this;
    }

    public function getTarifPrestation(): ?float
    {
        return $this->tarif_prestation;
    }

    public function setTarifPrestation(float $tarif_prestation): self
    {
        $this->tarif_prestation = $tarif_prestation;

        return $this;
    }

    



    /**
     * @return Collection|MateriauxNecessaires[]
     */
    public function getMateriauxNecessaires(): Collection
    {
        return $this->materiauxNecessaires;
    }

    public function addMateriauxNecessaire(MateriauxNecessaires $materiauxNecessaire): self
    {
        if (!$this->materiauxNecessaires->contains($materiauxNecessaire)) {
            $this->materiauxNecessaires[] = $materiauxNecessaire;
            $materiauxNecessaire->setTache($this);
        }

        return $this;
    }

    public function removeMateriauxNecessaire(MateriauxNecessaires $materiauxNecessaire): self
    {
        if ($this->materiauxNecessaires->removeElement($materiauxNecessaire)) {
            // set the owning side to null (unless already changed)
            if ($materiauxNecessaire->getTache() === $this) {
                $materiauxNecessaire->setTache(null);
            }
        }

        return $this;
    }

    public function getPrestataire(): ?Prestataire
    {
        return $this->prestataire;
    }

    public function setPrestataire(?Prestataire $prestataire): self
    {
        $this->prestataire = $prestataire;

        return $this;
    }

    public function getMetier(): ?Metier
    {
        return $this->metier;
    }

    public function setMetier(?Metier $metier): self
    {
        $this->metier = $metier;

        return $this;
    }

    /**
     * @return Collection|StockTacheUtilise[]
     */
    public function getStockTacheUtilises(): Collection
    {
        return $this->stockTacheUtilises;
    }

    public function addStockTacheUtilise(StockTacheUtilise $stockTacheUtilise): self
    {
        if (!$this->stockTacheUtilises->contains($stockTacheUtilise)) {
            $this->stockTacheUtilises[] = $stockTacheUtilise;
            $stockTacheUtilise->setTache($this);
        }

        return $this;
    }

    public function removeStockTacheUtilise(StockTacheUtilise $stockTacheUtilise): self
    {
        if ($this->stockTacheUtilises->removeElement($stockTacheUtilise)) {
            // set the owning side to null (unless already changed)
            if ($stockTacheUtilise->getTache() === $this) {
                $stockTacheUtilise->setTache(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Phase[]
     */
    public function getPhase(): Collection
    {
        return $this->phase;
    }

    public function addPhase(Phase $phase): self
    {
        if (!$this->phase->contains($phase)) {
            $this->phase[] = $phase;
        }

        return $this;
    }

    public function removePhase(Phase $phase): self
    {
        $this->phase->removeElement($phase);

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->statut;
    }

    public function setStatut(?Statut $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * The __toString method allows a class to decide how it will react when it is converted to a string.
     *
     * @return string
     * @link https://php.net/manual/en/language.oop5.magic.php#language.oop5.magic.tostring
     */
    public function __toString()
    {
        return $this->getNomTache(). " par ".$this->getPrestataire();
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }





    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(?\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getTacheDependante(): ?self
    {
        return $this->tache_dependante;
    }

    public function setTacheDependante(?self $tache_dependante): self
    {
        $this->tache_dependante = $tache_dependante;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(self $tach): self
    {
        if (!$this->taches->contains($tach)) {
            $this->taches[] = $tach;
            $tach->setTacheDependante($this);
        }

        return $this;
    }

    public function removeTach(self $tach): self
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getTacheDependante() === $this) {
                $tach->setTacheDependante(null);
            }
        }

        return $this;
    }


}

src/Form/TacheType.php
<?php

namespace App\Form;

use App\Entity\Tache;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TacheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_tache')
            ->add('tarif_prestation')
            ->add('StatutTache')
            ->add('metier')
            ->add('prestataire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tache::class,
        ]);
    }
}

src/Controller/TacheController.php
<?php

namespace App\Controller;

use App\Entity\Statut;
use App\Entity\Tache;
use App\Form\Tache1Type;
use App\Repository\StatutRepository;
use App\Repository\TacheRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/conduc/tache')]
class TacheController extends AbstractController
{
    #[Route('/', name: 'tache_index', methods: ['GET'])]
    public function index(TacheRepository $tacheRepository): Response
    {
        return $this->render('tache/index.html.twig', [
            'taches' => $tacheRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'tache_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $tache = new Tache();
        $form = $this->createForm(Tache1Type::class, $tache);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tache);
            $entityManager->flush();
            $route = $request->headers->get('referer');

            return $this->redirect($route);
            //return $this->redirectToRoute('tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tache/new.html.twig', [
            'tache' => $tache,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'tache_show', methods: ['GET'])]
    public function show(Tache $tache): Response
    {
        return $this->render('tache/show.html.twig', [
            'tache' => $tache,
        ]);
    }

    #[Route('/{id}/edit', name: 'tache_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Tache $tache): Response
    {
        $form = $this->createForm(Tache1Type::class, $tache);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $route = $request->headers->get('referer');

            return $this->redirect($route);
            //return $this->redirectToRoute('tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tache/edit.html.twig', [
            'tache' => $tache,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'tache_delete', methods: ['POST'])]
    public function delete(Request $request, Tache $tache): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tache->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tache);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tache_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tache/_delete_form.html.twig
<form method="post" action="{{ path('tache_delete', {'id': tache.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tache.id) }}">
    <button class="btn btn-outline-danger mx-auto">Supprimer</button>
</form>

templates/tache/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tache{% endblock %}

{% block body %}
    <h1>Edit Tache</h1>

    {{ include('tache/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tache_index') }}">back to list</a>

    {{ include('tache/_delete_form.html.twig') }}
{% endblock %}

templates/tache/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tache index{% endblock %}

{% block body %}
    <h1>Tache index</h1>
{{ dump(taches) }}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_tache</th>
                <th>Tarif_prestation</th>
                <th>Matériaux necessaires</th>
                <th>prestataire</th>
                <th>Metier</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tache in taches %}
            <tr>
                <td>{{ tache.id }}</td>
                <td>{{ tache.nomTache }}</td>
                <td>{{ tache.tarifPrestation }}</td>
                <td>
                    {% for m in tache.stockTacheUtilises  %}
                        <li>{{ m }}
                            <a class="btn btn-warning" href="{{ path('stock_tache_utilise_edit', {'id': m.id}) }}">M-A-J</a>
                        </li>
                    {% endfor %}
                    </td>
                <td>{{ tache.prestataire}}</td>
                <td>{{ tache.metier }}</td>
                <td>{{ tache.statut }}</td>

                <td>
                    <a class="btn btn-primary" href="{{ path('tache_show', {'id': tache.id}) }}">show</a>
                    <a class="btn btn-warning" href="{{ path('tache_edit', {'id': tache.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tache_new') }}">Create new</a>
{% endblock %}

templates/tache/new.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<br>
<h1 class="text-center">Nouvelle Tache</h1>
<br>

<table class="table table-bordered align-content-center mx-auto" style="width: 90%">
    <thead>
    <tr class="thead-dark ">
        <th scope="col">

            {{ include('tache/_form.html.twig') }}

            <button type="button" class="btn btn-outline-primary"><a href="{{ path('tache_index') }}">Retour à la liste</a></button>

        </th>
    </tr>
    </thead>
</table>

{% endblock %}

templates/tache/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tache{% endblock %}

{% block body %}
    <h1>Tache</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tache.id }}</td>
            </tr>
            <tr>
                <th>Nom_tache</th>
                <td>{{ tache.nomTache }}</td>
            </tr>
            <tr>
                <th>Tarif_prestation</th>
                <td>{{ tache.tarifPrestation }}</td>
            </tr>
            <tr>
                <th>Matériaux necessaires</th>
                <td>
                    {% for m in tache.stockTacheUtilises %}
                        <li>{{ m }} <a class="btn btn-warning" href="{{ path('stock_tache_utilise_edit', {'id': m.id}) }}">M-A-J</a></li>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Prestataires</th>
                <td>{{ tache.prestataire }}</td>
            </tr>
            <tr>
                <th>Métier</th>
                <td>{{ tache.metier }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ tache.statut }}</td>
            </tr>

        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('tache_index') }}">back to list</a>

    <a class="btn btn-warning"  href="{{ path('tache_edit', {'id': tache.id}) }}">edit</a>

    {{ include('tache/_delete_form.html.twig') }}
{% endblock %}