src/Entity/Unite.php
<?php

namespace App\Entity;

use App\Repository\UniteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UniteRepository::class)
 */
class Unite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_unite;

    /**
     * @ORM\OneToMany(targetEntity=Materiaux::class, mappedBy="unite")
     */
    private $materiauxes;

    public function __construct()
    {
        $this->materiauxes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomUnite(): ?string
    {
        return $this->nom_unite;
    }

    public function setNomUnite(string $nom_unite): self
    {
        $this->nom_unite = $nom_unite;

        return $this;
    }

    /**
     * @return Collection|Materiaux[]
     */
    public function getMateriauxes(): Collection
    {
        return $this->materiauxes;
    }

    public function addMateriaux(Materiaux $materiaux): self
    {
        if (!$this->materiauxes->contains($materiaux)) {
            $this->materiauxes[] = $materiaux;
            $materiaux->setUnite($this);
        }

        return $this;
    }

    public function removeMateriaux(Materiaux $materiaux): self
    {
        if ($this->materiauxes->removeElement($materiaux)) {
            // set the owning side to null (unless already changed)
            if ($materiaux->getUnite() === $this) {
                $materiaux->setUnite(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom_unite;
    }
}

src/Form/UniteType.php
<?php

namespace App\Form;

use App\Entity\Unite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UniteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_unite')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Unite::class,
        ]);
    }
}

src/Controller/UniteController.php
<?php

namespace App\Controller;

use App\Entity\Unite;
use App\Form\UniteType;
use App\Repository\UniteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/conduc/unite')]
class UniteController extends AbstractController
{
    #[Route('/', name: 'unite_index', methods: ['GET'])]
    public function index(UniteRepository $uniteRepository): Response
    {
        return $this->render('unite/index.html.twig', [
            'unites' => $uniteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'unite_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $unite = new Unite();
        $form = $this->createForm(UniteType::class, $unite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($unite);
            $entityManager->flush();

            return $this->redirectToRoute('unite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('unite/new.html.twig', [
            'unite' => $unite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'unite_show', methods: ['GET'])]
    public function show(Unite $unite): Response
    {
        return $this->render('unite/show.html.twig', [
            'unite' => $unite,
        ]);
    }

    #[Route('/{id}/edit', name: 'unite_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Unite $unite): Response
    {
        $form = $this->createForm(UniteType::class, $unite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('unite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('unite/edit.html.twig', [
            'unite' => $unite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'unite_delete', methods: ['POST'])]
    public function delete(Request $request, Unite $unite): Response
    {
        if ($this->isCsrfTokenValid('delete'.$unite->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($unite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('unite_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/unite/_delete_form.html.twig
<form method="post" action="{{ path('unite_delete', {'id': unite.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet item ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unite.id) }}">
    <button class="btn btn-outline-danger mx-auto">Supprimer</button>
</form>

templates/unite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Unite{% endblock %}

{% block body %}
    <h1>Edit Unite</h1>

    {{ include('unite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('unite_index') }}">back to list</a>

    {{ include('unite/_delete_form.html.twig') }}
{% endblock %}

templates/unite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Unite index{% endblock %}

{% block body %}
    <h1>Unite index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_unite</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for unite in unites %}
            <tr>
                <td>{{ unite.id }}</td>
                <td>{{ unite.nomUnite }}</td>
                <td>
                    <a href="{{ path('unite_show', {'id': unite.id}) }}">show</a>
                    <a href="{{ path('unite_edit', {'id': unite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('unite_new') }}">Create new</a>
{% endblock %}

templates/unite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Unite{% endblock %}

{% block body %}
    <h1>Create new Unite</h1>

    {{ include('unite/_form.html.twig') }}

    <a href="{{ path('unite_index') }}">back to list</a>
{% endblock %}

templates/unite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Unite{% endblock %}

{% block body %}
    <h1>Unite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ unite.id }}</td>
            </tr>
            <tr>
                <th>Nom_unite</th>
                <td>{{ unite.nomUnite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('unite_index') }}">back to list</a>

    <a href="{{ path('unite_edit', {'id': unite.id}) }}">edit</a>

    {{ include('unite/_delete_form.html.twig') }}
{% endblock %}